#! /usr/bin/python3

# Gerber query script
# Modified by ondra6ak
# Written by Matthew Beckler for Wayne and Layne, LLC
# Based on a script from @laen
# Released into the Public Domain. Have fun

import re
from sys import argv
from utils import gerbdim

if (len(argv) < 2) or ("-h" in argv):
    print("Usage: gerbdim [-h] [GERBERFILE]")
    exit()

dim = gerbdim(argv[1])
print("{} x {} mm".format(round(dim[0], 2), round(dim[1], 2)))
