#!/usr/bin/python3

from sys import argv

def mils2mm(mils):
    return mils / 1000 * 25.4

if __name__ == "__main__":
    if "-h" in argv:
        print("Usage: mils2mm [-h] [MILS]")
        print("If no argument is given, stdin is used instead")
        exit()

    if len(argv) < 2:
        mils = float(input())
    else:
        mils = float(argv[1])

    print(mils2mm(mils))
