#!/usr/bin/python3

from sys import argv

def mm2mils(mm):
    return mm * 1000 / 25.4

if __name__ == "__main__":
    if "-h" in argv:
        print("Usage: mm2mils [-h] [MM]")
        print("If no argument is given, stdin is used instead")
        exit()

    if len(argv) < 2:
        mm = float(input())
    else:
        mm = float(argv[1])
   
    print(mm2mils(mm))
